version: '3'

services:

  angrid:
    build: ./
    restart: always
    container_name: angrid_trading
    command: ["python3", "main.py"]
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    
      
  db:
    image: postgres:12
    restart: always
    container_name: angrid_database
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - .:/docker-entrypoint-initdb.d